name: Update README daily at 04:04 UTC

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '04 4 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: List files
        run: ls -la
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          
      - name: Install dependencies and update README
        working-directory: ./Melvynx-master
        run: |
          npm ci
          node index.js > README.md
          cp README.md ../
        env:
          CI: true
          
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Abdelfattah BEZZAZ
          author_email: abdelfatah.bezzaz@um5r.ac.ma
          add: 'README.md'
          message: ':memo: README.md updated automatically'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
